server.port=8080
spring.application.name=ms-digitalfix-bff

# Configuracion Azure AD
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/cc0041c5-4918-4ed1-9a20-23dc386471d4/discovery/v2.0/keys
# Modo chismoso para ver por que Azure rechaza el token
logging.level.org.springframework.security=DEBUG