# Puerto donde correrá el BFF
server.port=8080

# Nombre de la aplicación
spring.application.name=ms-digitalfix-bff

# -
# CONFIGURACIÓN DE SEGURIDAD (AZURE AD)
#
# 1. Valida la firma y el "issuer" usando tu Tenant ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/cc0041c5-4918-4ed1-9a20-23dc386471d4/v2.0

# 2. Audience 
app.security.audience=api://898e9076-6eb3-4901-a900-1017f8a7a2f6